[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm db:migrate:prod && node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environments.production]
numReplicas = 1
